Vagrant.configure("2") do | config |
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "Docker_NodeJS_Dev_Environment"
    config.vm.provision "shell", path: "provision.sh"
    config.vm.provider "virtualbox" do |v|
        v.name = "Docker_Host"
        v.memory 3000
    config.vm.network "forwarded_port", guest: 80, host: 8080
    end
end